# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id_val', models.AutoField(primary_key=True, serialize=False)),
                ('extension', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_val', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=250)),
                ('action', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('ip_address', models.IntegerField()),
            ],
        ),
    ]
